# roles/vsftpd/tasks/main.yml
---

- name: Ensure `listen` and `listen_ipv6` are mutually exclusive
  assert:
    that: "vsftpd_listen != vsftpd_listen_ipv6"
  tags: vsftpd

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml
  tags: vsftpd

- name: Install Vsftpd
  package:
    name: '{{ vsftpd_packages }}'
    state: present
  tags: vsftpd

- include: selinux.yml

- name: Ensure service is started
  service:
    name: '{{ vsftpd_service }}'
    state: started
    enabled: true
  tags: vsftpd

- name: Ensure `anon_root` exists
  file:
    path: '{{ vsftpd_anon_root }}'
    state: directory
    owner: root
    group: root
    mode: '0775'
    setype: '{{ vsftpd_setype }}'
  when: vsftpd_anon_root is defined
  tags: vsftpd

- name: Ensure `local_root` exists
  file:
    path: '{{ vsftpd_local_root }}'
    state: directory
    owner: root
    group: root
    mode: '0775'
    setype: '{{ vsftpd_setype }}'
  when: vsftpd_local_root is defined
  tags: vsftpd

- name: Install configuration file
  template:
    src:   etc_vsftpd_vsftpd.conf.j2
    dest: "{{ vsftpd_config_file }}"
    owner: root
    group: root
    mode: '0600'
    setype: etc_t
    #validate: 'vsftpd -olisten=NO %s'
  notify: restart vsftpd
  tags: vsftpd
