# roles/vsftpd/tasks/selinux.yml
---

- name: Allow full read/write access through SELinux
  seboolean:
    name: ftpd_full_access
    state: yes
    persistent: yes
  tags: vsftpd

  # in RHEL/CentOS 7.3, the SELinux boolean ftp_home_dir was removed and
  # access to home directories is enabled by default
  # See https://bugzilla.redhat.com/show_bug.cgi?id=1352257
- name: Check if ftp_home_dir exists
  shell: getsebool -a | grep '^ftp_home_dir\b'
  register: var_exists
  failed_when: false
  changed_when: false
  tags: vsftpd

- name: Allow access to home directories
  seboolean:
    name: ftp_home_dir
    state: yes
    persistent: yes
  when: var_exists.status == 0
  tags: vsftpd

